### ISSUE TITLE
run arguments must be separated.

### ISSUE THREAD

**Issue by sto3014** [competencytestlvl/webdriver_auto_update#12]
rund arguments must be separated (line 131): 
cmd_run = subprocess.run(args=["chromedriver", "--version"], capture_output=True, text=True)

**Comment by competencytestlvl** [comment]
Issue resolved in commit [5dae4be](https://github.com/competencytestlvl/webdriver_auto_update/commit/5dae4be7b519611d7a347a61c6f01f397213a021)
