### ISSUE TITLE
Autoupdate not working

### ISSUE THREAD

**Issue by Cassar88226** [competencytestlvl/webdriver_auto_update#18]
I installed webdriver_auto_update 1.2.0 in my env and tried to update the chromedriver.
But it failed with this error: urllib.error.HTTPError: HTTP Error 404: Not Found

In terminal, I see it is trying to download the chromedriver from this link :
https://edgedl.me.gvt1.com/edgedl/chrome/chrome-for-testing/121.0.6167.184/win64/chromedriver-win64.zip.

Could you please fix this issue in package or any suggestion?

**Comment by competencytestlvl** [comment]
Special thanks to @antoniopegorelli for the fix. @Cassar88226 Kindly refer to the latest commit. [0fccc5d](https://github.com/competencytestlvl/webdriver_auto_update/commit/0fccc5d87d3e11c3018cebafece0478670fc9697) The updates have been incorporated into the main branch https://github.com/competencytestlvl/webdriver_auto_update
