### ISSUE TITLE
incorrect os version driver installing

### ISSUE THREAD

**Issue by bigbadhamster** [competencytestlvl/webdriver_auto_update#2]
its downloading chromedriver.exe on ubuntu.
this is not "OS independent"

**Comment by ShanArosh2002** [comment]
you can use [https://github.com/ShanArosh2002/webdriver_auto_update] until the fix get pushed

**Comment by competencytestlvl** [comment]
@bigbadhamster Kindly refer to latest commit [53f9434](https://github.com/competencytestlvl/webdriver_auto_update/commit/53f9434e9f58cdee82f20aef7eb4e52d5883d1d0)

@ShanArosh2002 Thank you. Your contribution is highly appreciated. Feel free reach out if you have any more suggestions.
