### ISSUE TITLE
webdriver_auto_update is not accessing the new drivers due to url change

### ISSUE THREAD

**Issue by 7hunderForce** [competencytestlvl/webdriver_auto_update#8]
Before the package was checking for drivers here:
https://chromedriver.chromium.org/downloads

But now, all the new drivers are here:
https://googlechromelabs.github.io/chrome-for-testing/

Would you be so kind to update this library to continue to look for the newest Chrome driver?

**Comment by competencytestlvl** [comment]
@7hunderForce Kindly refer to the latest commit [78be506](https://github.com/competencytestlvl/webdriver_auto_update/commit/78be5067e3b59f9dac737a08e93f99c66b0ca16e) to access the latest stable version of chromedriver.
